chunksize: 100000
dedup_enabled: false
dedup_field: lastname
dedup_merge_columns: []
delimiter: ','
encoding: auto
estimate_total_rows: true
log_name: CPCsvDone.txt
min_length_columns:
- firstname
- lastname
min_length_enabled: true
min_length_value: 2
out_name: CPCsvDone.csv
profile: configs/profiles/uni.yaml
row_filter_one_filled_enabled: true
row_filter_subset:
- firstname
- lastname
- phone
- email
- street
- district
- locality
- region
- country
- zip
- address
save_dir: D:\Desktop
